import type {
  EnvContext,
  PlatformEndpoints,
  UrlContext,
  WorkspaceIdentity,
} from "../types";
import type { LoadedConfig } from "./config";
import { writeEnvSnapshot } from "../util/dotenv";

/**
 * Three layers, highest priority last:
 *
 *   1. the project's secrets file  — hand-managed, READ ONLY, never written
 *   2. the generated snapshot      — WorkTrellis-owned keys
 *   3. the process environment     — injected when WorkTrellis spawns a child
 *
 * The snapshot exists so tools WorkTrellis does not spawn (a database CLI, a
 * one-off script) resolve the same values without anyone editing a file by
 * hand, and without WorkTrellis ever writing to the secrets file.
 */

export interface EnvConflict {
  key: string;
  baseValue: string;
  ownedValue: string;
  severity: "critical" | "info";
}

export interface ResolvedEnv {
  /** Keys WorkTrellis owns and writes to the snapshot. */
  owned: Record<string, string>;
  /** Full environment for spawned children: secrets overlaid with owned keys. */
  combined: Record<string, string>;
  conflicts: EnvConflict[];
  /** Owned keys an explicit process variable overrode for this invocation. */
  overriddenByProcess: string[];
}

const SECRET_PATTERN = /(SECRET|TOKEN|PASSWORD|PEPPER|KEY(RING)?|CREDENTIAL)/i;

export function looksSecret(key: string): boolean {
  // Endpoint and prefix settings frequently contain "KEY" without being one.
  if (/^(S3_ENDPOINT|.*_KEY_PREFIX|.*_PUBLIC_KEY)$/i.test(key)) return false;
  return SECRET_PATTERN.test(key);
}

export function buildEnvContext(input: {
  identity: WorkspaceIdentity;
  services: PlatformEndpoints;
  url: UrlContext;
  baseEnv: Map<string, string>;
}): EnvContext {
  return {
    workspace: input.identity,
    services: input.services,
    url: input.url,
    baseEnv: Object.freeze(Object.fromEntries(input.baseEnv)),
  };
}

export function resolveEnv(
  config: LoadedConfig["config"],
  context: EnvContext,
  baseEnv: Map<string, string>,
): ResolvedEnv {
  const profile = config.env(context);
  const criticalKeys = new Set(config.criticalKeys ?? []);

  const owned: Record<string, string> = {};
  const conflicts: EnvConflict[] = [];

  for (const [key, value] of Object.entries(profile)) {
    // An undefined or empty value means "WorkTrellis has nothing to say about
    // this key", so the secrets file keeps whatever it had.
    if (value === undefined || value === "") continue;
    owned[key] = value;

    const baseValue = baseEnv.get(key);
    if (baseValue !== undefined && baseValue !== value) {
      conflicts.push({
        key,
        baseValue,
        ownedValue: value,
        severity: criticalKeys.has(key) ? "critical" : "info",
      });
    }
  }

  const combined: Record<string, string> = {
    ...Object.fromEntries(baseEnv),
    ...owned,
    ...context.url.providerEnv,
  };

  // Explicitly exported variables win, matching how env-file loaders behave:
  // they never override a real process variable. This applies to both generated
  // keys and secrets loaded from the base env file; otherwise `API_KEY=...`
  // would behave differently inside and outside WorkTrellis.
  //
  // Only `combined` honors the override. `owned` keeps the derived value, so a
  // one-off override is never baked into the snapshot other tools read.
  const overriddenByProcess: string[] = [];
  for (const [key, fromProcess] of Object.entries(process.env)) {
    if (fromProcess === undefined) continue;
    if (owned[key] !== undefined && fromProcess !== owned[key]) {
      overriddenByProcess.push(key);
    }
    combined[key] = fromProcess;
  }

  return { owned, combined, conflicts, overriddenByProcess };
}

export function writeSnapshot(
  snapshotPath: string,
  owned: Record<string, string>,
  identity: WorkspaceIdentity,
): void {
  writeEnvSnapshot(snapshotPath, owned, {
    header: [
      "Generated by WorkTrellis. DO NOT EDIT, and do not commit.",
      "",
      `workspace  ${identity.slug}`,
      `worktree   ${identity.root}`,
      "",
      "These values are derived from worktrellis.config.ts and this machine's",
      "shared services. Edit the config, not this file. Secrets stay in the",
      "project's own env file, which WorkTrellis never writes.",
    ],
  });
}

/** Present a value without disclosing a secret. */
export function displayValue(key: string, value: string): string {
  if (looksSecret(key)) return `<set, ${value.length} chars>`;

  // Credentials embedded in a URL are still credentials.
  return value.replace(/(\/\/[^:/@]+:)([^@]+)(@)/, "$1***$3");
}
